//! `maapp schema` — the canonical machine-readable contract emitter.
//!
//! Generates the JSON Schema (draft 2020-12) for a maapp-graph document from
//! the SAME Rust vocabulary tables `validate` enforces (`core_node_kinds`,
//! `core_edges`, `refs_keys`, the provenance shape, the A4 version window) —
//! never a hand-authored parallel schema that can drift. The committed artifact
//! `schema/maapp-graph.schema.json` is byte-locked to this emitter by a test;
//! editing a table without re-emitting the artifact turns the suite red.
//!
//! Determinism: every table-derived map is built by iterating a `BTreeMap`
//! (sorted keys); literal keyword objects are written with keys in sorted
//! order. `serde_json`'s `preserve_order` keeps insertion order, so the emit is
//! byte-stable across runs and machines. Selectional from/to kind sets are
//! cross-node constraints JSON Schema cannot express; they ride along as
//! `x-maapp-fromKinds`/`x-maapp-toKinds` annotation keywords (legal in
//! 2020-12: unknown keywords are collected as annotations) and are enforced by
//! `maapp validate` (`E_KIND`).

use crate::error::EngineError;
use crate::graph::{core_edges, core_node_kinds, provenance_origins, refs_keys, trigger_causes};
use crate::model::LAYERS;
use crate::validate::{KNOWN_MAJOR, KNOWN_MINOR_MAX};
use serde_json::{Map, Value, json};
use std::collections::BTreeMap;

/// The canonical schema id (D-001). The `<app>-graph` suffix acceptance is a
/// compat rule, not canon — see the emitted schema's `description`.
pub const SCHEMA_ID: &str = "maapp-graph";

/// Emit the canonical schema as pretty-printed bytes + one trailing newline
/// (the exact bytes `maapp schema` prints and `schema/maapp-graph.schema.json`
/// commits).
pub fn schema_bytes() -> Result<Vec<u8>, EngineError> {
    let mut buf = serde_json::to_vec_pretty(&schema_value())?;
    buf.push(b'\n');
    Ok(buf)
}

/// Build the canonical JSON Schema document from the engine tables.
pub fn schema_value() -> Value {
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": SCHEMA_ID,
        "title": "maapp graph document",
        "description": format!(
            "Canonical JSON Schema for a maapp-graph document (schema version {KNOWN_MAJOR}.{KNOWN_MINOR_MAX}), generated by `maapp schema` from the engine's Rust vocabulary tables — the same tables `maapp validate` enforces (single source of truth; do not hand-edit). The canonical schema id is 'maapp-graph'; the engine also accepts any per-app '<app>-graph' id — that suffix acceptance is a compat rule, not canon. Selectional edge from/to kind sets are cross-node constraints JSON Schema cannot express; they are carried as x-maapp-fromKinds/x-maapp-toKinds annotations and enforced by `maapp validate` (E_KIND)."
        ),
        "type": "object",
        "required": ["schema", "version"],
        "properties": top_level_properties(),
        "$defs": defs(),
    })
}

/// The five canonical layers, sorted.
fn sorted_layers() -> Vec<&'static str> {
    let mut layers = LAYERS.to_vec();
    layers.sort_unstable();
    layers
}

/// Top-level document properties, keys sorted.
fn top_level_properties() -> Value {
    let mut props = Map::new();
    props.insert(
        "attrEnumRegistry".to_string(),
        json!({
            "type": "object",
            "description": "Declarative closed-enum extensions (open-with-registry): '<verb>.<attr>' (or '<Kind>.<attr>' for node attrs, e.g. 'Trigger.cause') → list of declared tokens. A non-core value in a closed-enum position is E_ATTR_ENUM (E_TRIGGER_CAUSE for Trigger.cause) unless declared here (data overlays, never code plugins). Namespace NEW tokens 'x-<ns>:token' (collision-safe against future core values); bare tokens are accepted for domain-specific vocabularies.",
            "additionalProperties": {
                "type": "array",
                "items": {"type": "string"}
            }
        }),
    );
    props.insert(
        "edgeRegistry".to_string(),
        json!({
            "type": "object",
            "description": "Declarative edge-verb extensions: 'x-<ns>:verb' → row (data overlays, never code plugins).",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "family": {"type": "string"},
                    "from_kinds": {"type": "array", "items": {"type": "string"}},
                    "subPropertyOf": {"type": "string", "description": "Core verb this extension specializes (e.g. surface-openers chain to navigates/returnsTo)."},
                    "to_kinds": {"type": "array", "items": {"type": "string"}}
                },
                "additionalProperties": true
            }
        }),
    );
    props.insert(
        "edges".to_string(),
        json!({
            "type": "array",
            "description": "The flat typed-edge array (document order is meaningful: findings and branch-set grouping follow it).",
            "items": {"$ref": "#/$defs/edge"}
        }),
    );
    props.insert(
        "meta".to_string(),
        json!({
            "type": "object",
            "description": "Author-owned metadata. Only the keys below are engine-read; everything else passes through.",
            "properties": {
                "flows": {
                    "type": "array",
                    "items": {"$ref": "#/$defs/flow"},
                    "description": "First-class named journeys. Shape violations are E_FLOW_*; a declared terminal/via the trace traversal cannot reach from the entry is the advisory W_FLOW_UNREACHABLE. `validate --json` reports the declared count as 'flows' (omitted when zero)."
                },
                "lints": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Opt-in advisory lint packs (e.g. 'slice-coverage', 'design-completeness')."
                },
                "provenance": {"$ref": "#/$defs/provenance"},
                "slice_of": {"$ref": "#/$defs/sliceOf"},
                "waivers": {
                    "type": "array",
                    "items": {"$ref": "#/$defs/waiver"},
                    "description": "The warning baseline: advisory findings waived by (code, node). A waived advisory reports as severity 'waived' with a visible count — never silent, never exit-code-relevant."
                }
            },
            "additionalProperties": true
        }),
    );
    props.insert(
        "nodeKindRegistry".to_string(),
        json!({
            "type": "object",
            "description": "Declarative node-kind extensions: 'x-<ns>:Name' → row (data overlays, never code plugins).",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "attrs": {"type": "object", "description": "Declared attr enums (e.g. 'outcome' for boundary returnsTo arms)."},
                    "layer": {"enum": sorted_layers()},
                    "legal_in_edges": {"type": "array", "items": {"type": "string"}},
                    "legal_out_edges": {"type": "array", "items": {"type": "string"}}
                },
                "additionalProperties": true
            }
        }),
    );
    props.insert("nodes".to_string(), nodes_schema());
    props.insert(
        "refsRegistry".to_string(),
        json!({
            "type": "object",
            "description": "Declarative refs-key extensions (open-with-registry, A3): key → row. A registry-declared key's VALUE shape is app-owned.",
            "additionalProperties": {
                "type": "object",
                "properties": {"description": {"type": "string"}},
                "additionalProperties": true
            }
        }),
    );
    props.insert(
        "schema".to_string(),
        json!({
            "type": "string",
            "pattern": "^.+-graph$",
            "description": "Schema id. Canonical: 'maapp-graph'. Any non-empty '<app>-graph' prefix is accepted as a compat rule."
        }),
    );
    props.insert(
        "version".to_string(),
        json!({
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+$",
            "description": format!(
                "MAJOR.MINOR string. This engine supports major {KNOWN_MAJOR}, minors 0-{KNOWN_MINOR_MAX}; an unknown minor of a known major validates with advisory W_VERSION_MINOR only (additive-minor policy)."
            )
        }),
    );
    Value::Object(props)
}

/// `nodes`: the per-layer node maps, layer keys sorted, each annotated with
/// its frozen-core kind set (derived from `core_node_kinds`).
fn nodes_schema() -> Value {
    // Invert kind → layer into layer → sorted kinds. BTreeMaps end to end.
    let mut by_layer: BTreeMap<&'static str, Vec<&'static str>> =
        LAYERS.iter().map(|l| (*l, Vec::new())).collect();
    for (kind, layer) in core_node_kinds() {
        by_layer.entry(layer).or_default().push(kind);
    }
    let mut layer_props = Map::new();
    for (layer, mut kinds) in by_layer {
        kinds.sort_unstable();
        layer_props.insert(
            layer.to_string(),
            json!({
                "type": "object",
                "additionalProperties": {"$ref": "#/$defs/node"},
                "x-maapp-coreKinds": kinds
            }),
        );
    }
    json!({
        "type": "object",
        "description": "Nodes filed by layer: nodes.<layer>.<slug> → node. A core kind filed under the wrong layer is E_LAYER_MISMATCH; node ids are unique across ALL layers (E_DUP_ID).",
        "properties": Value::Object(layer_props),
        "additionalProperties": {
            "type": "object",
            "additionalProperties": {"$ref": "#/$defs/node"}
        }
    })
}

/// `$defs`, keys sorted: edge, flow, node, provenance, refs, sliceOf,
/// sourceAnchor, waiver.
fn defs() -> Value {
    let mut defs = Map::new();
    defs.insert("edge".to_string(), edge_def());
    defs.insert("flow".to_string(), flow_def());
    defs.insert("node".to_string(), node_def());
    defs.insert("provenance".to_string(), provenance_def());
    defs.insert("refs".to_string(), refs_def());
    defs.insert("sliceOf".to_string(), slice_of_def());
    defs.insert("sourceAnchor".to_string(), source_anchor_def());
    defs.insert("waiver".to_string(), waiver_def());
    Value::Object(defs)
}

/// One closed `meta.flows` entry (keys sorted): a named journey (schema 1.4,
/// RES-003 2.4).
fn flow_def() -> Value {
    json!({
        "type": "object",
        "description": "One named end-to-end journey. `entry` must resolve to a Screen or a ROOT Trigger (no handles in-edge; E_FLOW_ENTRY); every slug must resolve (E_FLOW_UNRESOLVED); names are unique (E_FLOW_DUP_NAME); other shape violations are E_FLOW_MALFORMED. Reachability from entry over the q_trace edge family is derived at validate time (advisory W_FLOW_UNREACHABLE).",
        "required": ["entry", "name", "terminals"],
        "properties": {
            "entry": {"type": "string", "description": "The Screen (user lands) or root-Trigger (system event, attrs.cause) slug where the journey starts."},
            "name": {"type": "string", "description": "Unique flow name (the stable id a consumer/eval scores against)."},
            "terminals": {"type": "array", "items": {"type": "string"}, "minItems": 1, "description": "Substrate/end slugs the journey must reach."},
            "via": {"type": "array", "items": {"type": "string"}, "description": "Optional intermediate waypoint slugs (also reachability-checked)."}
        },
        "additionalProperties": false
    })
}

/// The closed `meta.slice_of` annotation stamped by `maapp export --slice`
/// (keys sorted). Presence puts `validate` in slice mode.
fn slice_of_def() -> Value {
    json!({
        "type": "object",
        "description": "Slice annotation stamped by `maapp export --slice` (LIFECYCLE-VERBS-SPEC §5). Presence puts validate in slice mode: W_ORPHAN is suppressed (slicing creates boundary orphans by construction). Shape violations are E_SLICE_OF_MALFORMED.",
        "required": ["selector"],
        "properties": {
            "depth": {"type": "integer", "minimum": 0, "description": "Neighborhood depth (slug-selector form only; scope slices carry no depth)."},
            "selector": {"type": "string", "description": "The slice selector: a node slug (BFS neighborhood) or 'scope:<scope>' (all *:<scope>/* nodes)."}
        },
        "additionalProperties": false
    })
}

/// One closed `meta.waivers` entry (keys sorted). The warning baseline
/// (RES-004 friction #9): declarative data, never code (D-003).
fn waiver_def() -> Value {
    json!({
        "type": "object",
        "description": "One advisory waiver: the named W_* finding on the named node reports as 'waived' (visible in the report's waived count) instead of a warning. E_* codes are NEVER waivable (E_WAIVER_FORBIDDEN); shape violations are E_WAIVER_MALFORMED.",
        "required": ["code", "node", "reason"],
        "properties": {
            "code": {"type": "string", "pattern": "^W_", "description": "The W_* advisory code being waived."},
            "node": {"type": "string", "description": "The node slug the finding names (must appear in the finding's ids)."},
            "reason": {"type": "string", "description": "Why this advisory is accepted — the audit trail, never optional."}
        },
        "additionalProperties": false
    })
}

/// One node, kind-checked against the frozen core ∪ 'x-' registry escape.
/// Carries the engine-read node-attr enums as if/then signatures (currently
/// one: `Trigger.attrs.cause`, schema 1.4 F1).
fn node_def() -> Value {
    let mut kinds: Vec<&'static str> = core_node_kinds().keys().copied().collect();
    kinds.sort_unstable();
    let mut causes: Vec<&'static str> = trigger_causes().to_vec();
    causes.sort_unstable();
    json!({
        "type": "object",
        "required": ["kind"],
        "properties": {
            "attrs": {"type": "object", "description": "Author-owned attributes (e.g. a declarative 'surface' taxonomy)."},
            "intent": {"type": "string", "description": "One-line human intent."},
            "kind": {
                "anyOf": [
                    {"enum": kinds},
                    {"type": "string", "pattern": "^x-", "description": "nodeKindRegistry-declared extension kind."}
                ]
            },
            "refs": {"$ref": "#/$defs/refs"}
        },
        "additionalProperties": true,
        "allOf": [{
            "if": {"properties": {"kind": {"const": "Trigger"}}, "required": ["kind"]},
            "then": {
                "properties": {
                    "attrs": {
                        "properties": {
                            "cause": {
                                "anyOf": [
                                    {"enum": causes},
                                    {"type": "string", "description": "Extension cause; legal ONLY if declared under 'Trigger.cause' in the graph's attrEnumRegistry (undeclared values are E_TRIGGER_CAUSE; x-<ns>:token recommended)."}
                                ],
                                "description": "What summons this Trigger. A Trigger with NO handles in-edge is a legal ROOT when it carries a cause: it models a system-initiated entry point (webhook/cron/callback/...) and is a legal flow entry + trace root."
                            }
                        }
                    }
                }
            }
        }]
    })
}

/// The closed `meta.provenance` trust stamp (keys sorted).
fn provenance_def() -> Value {
    json!({
        "type": "object",
        "description": "Trust stamp: who/what produced this graph. Every value is AUTHORED data — the engine never computes commits or timestamps (determinism rule). Unknown keys are E_PROVENANCE_KEY.",
        "required": ["origin"],
        "properties": {
            "asOf": {"type": "string", "description": "Source-repo SHA at last sync (LIFECYCLE-VERBS-SPEC §6.2): check-drift's base rev, bumped by `maapp stamp` / lifecycle updates. Distinct from sourceCommit (the ingest-time origin commit)."},
            "fidelity": {"type": "number", "minimum": 0, "maximum": 1, "description": "Authored 0..=1 estimate of ingest completeness."},
            "generatedAt": {"type": "string", "description": "Authored timestamp string (never engine-computed)."},
            "origin": {
                "enum": provenance_origins(),
                "description": "generated = LLM-authored from a brief; ingested = derived from a real codebase (enables the advisory W_ANCHORLESS anchor lint); ratified = human-reviewed and signed off."
            },
            "sourceCommit": {"type": "string", "description": "Commit of the source codebase an ingested graph was derived from."}
        },
        "additionalProperties": false
    })
}

/// The closed-key refs block (core keys sorted; registry keys legal via
/// `refsRegistry`, which JSON Schema cannot cross-reference).
fn refs_def() -> Value {
    let mut keys: Vec<&'static str> = refs_keys();
    keys.sort_unstable();
    let mut props = Map::new();
    for key in keys {
        props.insert(key.to_string(), refs_key_subschema(key));
    }
    json!({
        "type": "object",
        "description": "Closed-key refs block: the core keys below, plus any key declared in the graph's refsRegistry (undeclared non-core keys are E_REFS_KEY). Use {} when empty.",
        "properties": Value::Object(props),
        "additionalProperties": true
    })
}

/// Per-core-key refs subschema. Form patterns mirror the `check_ref_form` /
/// `check_source_form` checks in `validate`.
fn refs_key_subschema(key: &str) -> Value {
    match key {
        "design" => json!({
            "type": "string",
            "pattern": "^(file:|figma:|render:)",
            "description": "Design anchor: file:<path> | figma:<key/node> | render:<id> (E_REFS_FORM)."
        }),
        "decision" => json!({
            "type": "string",
            "description": "Graph-internal decision id, e.g. 'ADR-008' / 'D-003' / 'PLAN-2' (advisory W_REFS_FORM)."
        }),
        "slice" => json!({
            "type": "string",
            "pattern": "^S[0-9A-Za-z]+$",
            "description": "Walking-skeleton slice id, e.g. 'S0' (E_REFS_FORM)."
        }),
        "source" => json!({
            "anyOf": [
                {"$ref": "#/$defs/sourceAnchor"},
                {"type": "array", "items": {"$ref": "#/$defs/sourceAnchor"}}
            ],
            "description": "Core source anchor(s) tying the node to code: one anchor or an array. Required in spirit for ingested graphs (advisory W_ANCHORLESS on Screen/StateStore/BackendOp/Assertion when meta.provenance.origin='ingested')."
        }),
        _ => json!({"type": "string"}),
    }
}

/// One repo-relative source anchor string.
fn source_anchor_def() -> Value {
    json!({
        "type": "string",
        "pattern": "^[^#@]+(#L[0-9]+(-L[0-9]+)?|@.+)?$",
        "not": {"anyOf": [{"pattern": "^/"}, {"pattern": "(^|/)\\.\\.(/|#|@|$)"}]},
        "description": "Repo-relative source anchor: 'relative/path.ext' + optional '#L<start>', '#L<start>-L<end>' or '@<symbol>'. Absolute paths and '..' segments are E_REFS_FORM. Existence on disk is NOT checked by validate (repo-independent + deterministic); drift detection is the future check-drift verb's job."
    })
}

/// One typed edge, with the full frozen-core signature table as if/then
/// entries (verb-sorted via the `core_edges` BTreeMap).
fn edge_def() -> Value {
    let mut verbs: Vec<&'static str> = core_edges().keys().copied().collect();
    verbs.sort_unstable();

    let mut all_of: Vec<Value> = Vec::new();
    for (verb, sig) in core_edges() {
        let mut then = Map::new();
        let mut req: Vec<&'static str> = sig.req.clone();
        req.sort_unstable();
        if !req.is_empty() {
            then.insert("required".to_string(), json!(req));
        }
        let mut enum_props: BTreeMap<&'static str, Value> = BTreeMap::new();
        for (attr, vals) in &sig.enums {
            let mut sorted_vals = vals.clone();
            sorted_vals.sort_unstable();
            enum_props.insert(
                attr,
                json!({
                    "anyOf": [
                        {"enum": sorted_vals},
                        {"type": "string", "description": format!("Extension value; legal ONLY if declared under '{verb}.{attr}' in the graph's attrEnumRegistry (undeclared non-core values are E_ATTR_ENUM; namespace NEW tokens x-<ns>:, bare tokens are accepted for domain-specific vocabularies).")},
                        {"const": "else", "description": "Branch-set default arm."}
                    ]
                }),
            );
        }
        if verb == "emits" {
            // DECISION (RES-003 2.1 follow-up): `emits.effect` stays an OPEN,
            // validator-UNCHECKED string, documented here instead of being
            // enforced. The emits signature deliberately carries no effect enum
            // ("open-with-registry; not hard-checked"). Enforcing it (even
            // open-with-registry) would false-positive on legitimate graphs:
            // real fixtures carry values like `x-ios:liveActivity` and `push` —
            // a non-x value no registry could admit. The field is a descriptive
            // hint, not a dispatch contract.
            enum_props.insert(
                "effect",
                json!({
                    "type": "string",
                    "description": "Open side-effect hint (SCHEMA.md suggests analytics, haptic, log, notification, toast, clipboard, systemShare, openURL, externalApp, timer — any app-specific value incl. x-* is also legal). Deliberately NOT validator-checked."
                }),
            );
        }
        if !enum_props.is_empty() {
            let props: Map<String, Value> = enum_props
                .into_iter()
                .map(|(k, v)| (k.to_string(), v))
                .collect();
            then.insert("properties".to_string(), Value::Object(props));
        }
        let mut from = sig.from.clone();
        from.sort_unstable();
        let mut to = sig.to.clone();
        to.sort_unstable();
        then.insert("x-maapp-fromKinds".to_string(), json!(from));
        then.insert("x-maapp-toKinds".to_string(), json!(to));
        all_of.push(json!({
            "if": {"properties": {"type": {"const": verb}}, "required": ["type"]},
            "then": Value::Object(then)
        }));
    }

    json!({
        "type": "object",
        "description": "Typed edge {type, from, to, attrs…}. Endpoints must resolve to node ids (E_DANGLING); the from/to KIND sets per verb are the x-maapp-fromKinds/x-maapp-toKinds annotations below, enforced by validate (E_KIND). Empty kind-set = any kind.",
        "required": ["from", "to", "type"],
        "properties": {
            "from": {"type": "string"},
            "to": {"type": "string"},
            "type": {
                "anyOf": [
                    {"enum": verbs},
                    {"type": "string", "pattern": "^x-", "description": "edgeRegistry-declared extension verb."}
                ]
            },
            "when": {"type": "string", "description": "Branch guard: an Assertion id (navigates), an outcome token (x-ext:returnsTo), or the literal \"else\". Branch sets are all-conditional + mutually exclusive (E_BRANCH_*)."}
        },
        "additionalProperties": true,
        "allOf": all_of
    })
}
